getopts to getopt

diff --git a/bin/odoosyncall b/bin/odoosyncall
--- a/bin/odoosyncall
+++ b/bin/odoosyncall
@@ -1,29 +1,71 @@
 #!/bin/bash
 ################################################################################
-# A sentence or two about the script
-################################################################################
 
-source /etc/odoo/odoo.tools
-
-##
-
+synopsis (){
+  echo "Sync list of Odoo projects to other installation. Excludes .git folders."
+}
 usage() { echo "Usage: $0 [-h <host>]" 1>&2; exit 1; }
-#[ -f /etc/odoo/odoo.tools ] && . /etc/odoo/odoo.tools
+
+## Test if conf exist so we don't garble stuff
+if [ -f /etc/odoo/odoo.tools ];
+then
+  source /etc/odoo/odoo.tools
+else
+  echo "Configuration /etc/odoo/odoo.tools not found"
+  exit -1
+fi
+
 
 ##
-local OPTIND
-local OPTARG
-local option
-while getopts ":h:" option; do
-    case $option in
-        h) HOST=${OPTARG} ; echo "Host: $option $OPTARG" ;;
-        \:) echo "Option $option requires an argument" ; return ;;
-        \?) echo "Illegal argument ${option}::${OPTARG}" ; return ;;
-    esac
+SHORT_ARGS='h:'
+LONG_ARGS='help,host:'# Comma separated
+
+# Dev. note: Based on /usr/share/doc/util-linux/examples/getopt-parse.bash
+# And getopt != getopts
+options=$(getopt -o "$SHORT_ARGS" --long "$LONG_ARGS" -- "$@")
+if [ $? -ne 0 ]; then
+	echo 'getopt could not parse input. Terminating...' >&2
+	exit 1
+fi
+eval set -- "$options" # Changing positional params to getopt filtered version of them.
+unset options # We don't need the options any more.
+
+# consume 1-2 positional params as flags at the time until there are no more.
+while true
+do
+	case "$1" in
+		'-h' | '--host' )
+			HOST=$2
+            shift 2 ; continue ;;
+		'--help' )
+			synopsis
+            usage
+            shift
+            exit 0 # Success
+            ;;
+		'--') # End of flagged params
+			shift
+			break # Break while loop
+			;; # Put here because it doesn't feel right to remove it
+		*)
+			echo "Internal error parsing input. Terminating ..." >&2
+			exit 1
+	esac
 done
+# echo "Positional parameters:"
+# for arg in "$@"
+# do
+# 	echo $arg
+# done
+if [ ! -z "$HOST" ]; then
+    echo "Sync target not set. Exiting ..."
+    exit 1
+fi
+## -------------------------------------------------------------------------- ##
+
 if [ ! -z "$ODOOADDONS" ]; then
     for p in ${ODOOADDONS//,/ }; do
-        echo -n $p " "
+        echo -n "$p "
         sudo chown odoo:odoo $p -R
         rsync -ar --delete --exclude='.git/' $p $HOST:$ADDONS_PATH_PREFIX
     done
